//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_S
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Request
    {
        public int ID { get; set; }
        public string Request { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
